const SIAQuestions = [
    ["Number of people directly employed in different project activities", "SIA012"],
    ["Number of households in your community reporting increased income", "SIA016"],
    ["Number of women in employment through DBC-1 Project business linkages", "SIA044"],
    ["Number of women directly employed by Sindh Forest Department (SFD) and DBC-1 Project in different project interventions", "SIA045"],
    ["Number of women reporting increased social and economic empowerment", "SIA046"],
    ["% of Women directly benefiting from DBC-1 Project interventions", "SIA047"],
    ["Number of daily wage earners and landless poor in employment because of project activities", "SIA062"],
    ["% of Daily wage laborers and landless poor with enhanced and diversified income and livelihood sources", "SIA065"],
    ["Number of daily wage-paid laborers positively impacted", ""],
    ["Number of landless/poor/marginalized and vulnerable groups people positively impacted", ""],
    ["Number of youth community members positively impacted", ""],
    ["Number of women and girls positively impacted", ""],
    ["Number of borrowers and debtors positively impacted", ""],
    ["Number of community members trained in alternative livelihoods", "SIA015"],
    ["Number of daily wage-earning laborers directly employed in DBC-1 project activities", "SIA063"],
    ["Number of poor, landless, marginalized and vulnerable groups people directly employed in DBC-1 project activities", "SIA064"],
    ["Number of community members and fishermen with decreased debt obligations", "SIA031"],
    ["Number of fishermen able to access open market and get better price for their catch", "SIA032"],
    ["Number of fishermen directly benefiting from mangrove restoration and DBC-1 Project", "SIA034"],
    ["% Fishermen reporting increased consistency in catch", "SIA035"],
    ["How many people amongst/of you are aware of the fact that mangrove restoration in the Delta Area will to increased and stable fisheries catch per unit of fishing effort", "SIA074"],
    ["Number of fishermen community members positively impacted", ""],
    ["Participatory Development of one set of guidelines and standards for sustainable fishing practices", "SIA023"],
    ["Number of awareness raising and training and capacity building sessions held and marine biodiversity conservation and adaptive management of Marine Protected Areas", "SIA025"],
    ["Number of Fishing Stewardship Committees (FSCs) adhering to agreed terms", "SIA026"],
    ["Number of fishermen attending awareness raising sessions that have been held", "SIA027"],
    ["Number of fishermen with greater appreciation of sustainable fishing practices", "SIA028"],
    ["Number of nets with proper mesh size distributed", "SIA029"],
    ["Number of FSCs linked to microfinance schemes", "SIA030"],
    ["Number of Fish Cold Storage Facilities in the Project Zone", "SIA033"],
    ["Reduction in number of instances of infant and maternal mortality during birth", "SIA038"],
    ["Number of women reporting reduced health related issues", "SIA039"],
    ["Number and % of community members benefiting from health-related interventions", "SIA007"],
    ["Number of people with easy access to clean drinking water", "SIA009"],
    ["Number of people with better sanitation and hygiene facilities as a result of the restoration of RO plant", "SIA010"],
    ["Number of Women Organizations formed", "SIA036"],
    ["VDCs and their members are demonstrating greater appreciation of coastal and marine ecosystems and their resources and goods and services", "SIA067"],
    ["Number of VDCs demonstrating greater appreciation of coastal and marine ecosystems and their goods and services", "SIA068"],
    ["Number of VDCs directly benefiting from DBC-1 Project", "SIA069"],
    ["Number of community members and other visitors aware about Project Zone Cultural History and significance and visiting the conserved Island Fort", "SIA073"],
    ["How many people amongst/of you are aware of the fact mangroves restoration contributes to reducing shoreline erosion which is caused by climate change", "SIA075"],
    ["How many people amongst/of you are aware of the fact that mangroves restoration will contribute to reducing the area of landscape damaged by increased floods and tidal action caused by climate change", "SIA076"],
    ["How many people amongst/of you are aware of the fact that mangrove forests when restored in the area will help in reducing sea/salt water intrusion into agricultural lands", "SIA077"],
    ["How many people amongst/of you know the fact that mangrove restoration in the Indus Delta will help in reducing the number of people who will be forced to migrate because of the negative impacts of climate change on your communities and livelihoods sources", "SIA078"],
    ["Number of people in the community reporting that there are no negative impacts on HCV-4 Areas due to project activities: Areas important for the provision of regulating and supporting services by mangrove ecosystems", "SIA-HCV04"],
    ["Number of people in the community reporting that there are no negative impacts on HCV-5 Areas due to project activities: Areas which are important for meeting basic needs of local communities on account of provisioning services of mangrove forests", "SIA-HCV-05"],
    ["Number of people in the community reporting that there are no negative impacts on HCV-6 Areas due to project activities: Areas which are important for the provision of cultural, recreational and informational ecosystems services by mangrove forests", "SIA-HCV0"],
    ["Number of people in the community reporting that there are positive impacts of project activities on the conservation, restoration and sustainable management of community related HCVs Areas", "SIA-HCV04 to HCV06"],
    ["Do you agree to and endorse the mitigation measures suggested for fuelwood collectors, livestock grazers, and wildlife poachers and will they mitigate the short-term negative impact on this group of people", ""],
    ["Do you agree to and endorse the mitigation measures suggested for changing the behavior of traders, middlemen and employers? And do you think that the suggested measures will help in changing the behavior of traders, middlemen and employers", ""],
    ["Do you think that awareness raising and advocacy work for bringing about behavioral changes in the upstream dwellers are needed? And do you support the awareness raising and advocacy work for bringing about behavioral changes so that environmental water flows into the Delta Area can be ensured", ""]
];

export default SIAQuestions;